### ISSUE TITLE
Bintray is deprecated

### ISSUE THREAD

**Issue by xakod** [canmor-conan/conan-hidapi#2]
Bintray is deprecated https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ so we cannot retrive package after May 1st.
Maybe it will be better place for hidapi https://conan.io/center/

**Comment by canmor** [comment]
Thanks for your kindly remind and suggestion, I will try to move it to Conan Center in the next few days.

**Comment by canmor** [comment]
hidapi is merged into Conan Center now. Thanks for your help.
